-- Site update: Site live in production (2026-09-05)
-- Generated by scripts\new-site-update.ps1 - table lives in 0016_help_content.sql

INSERT INTO site_updates (version, kind, title_en, title_th, body_en, body_th, released_at) VALUES
('v0.6.0', 'feature',
 'Site live in production',
 'เว็บขึ้นใช้งานจริง',
 'The site now runs in production instead of a local preview, shipped together with a round of UX/UI work: case study pages gained a section navigation panel, and project covers and labels were tidied up.',
 'เว็บถูกนำขึ้นใช้งานจริงบนเซิร์ฟเวอร์แทนการเปิดดูในเครื่อง พร้อมกับงานปรับ UX/UI อีกชุด ทั้งแผงแท็บนำทางหัวข้อในหน้ารายละเอียดโปรเจกต์ และการจัดระเบียบภาพปกกับป้ายหัวข้อของโปรเจกต์',
 '2026-09-05');