<#
  Scaffold the next migration that records ONE site update (a row in site_updates).

  Run this whenever the site changes: the generated migration is applied on the
  next backend boot, and the entry then shows up on /help and /th/help in both
  languages without any frontend change. Table schema: backend/migrations/0016_help_content.sql

  Example:
    powershell -File scripts\new-site-update.ps1 -Version v0.6.0 -Kind feature `
      -TitleEn "Dark mode" -TitleTh "โหมดมืด" `
      -BodyEn "Every page follows the system theme." -BodyTh "ทุกหน้าปรับตามธีมของเครื่อง"

  Or through the Makefile:
    make update-note TITLE_EN="Dark mode" TITLE_TH="โหมดมืด" VERSION=v0.6.0 KIND=feature
#>
param(
    [Parameter(Mandatory = $true)][string]$TitleEn,
    [Parameter(Mandatory = $true)][string]$TitleTh,
    [string]$BodyEn = "",
    [string]$BodyTh = "",
    [string]$Version = "",
    [ValidateSet("feature", "improvement", "fix", "content")][string]$Kind = "feature",
    # Release date shown on the page, YYYY-MM-DD. Defaults to today.
    [string]$ReleasedAt = (Get-Date -Format "yyyy-MM-dd")
)

$root = Split-Path -Parent $PSScriptRoot
$migrationsDir = Join-Path $root "backend\migrations"

# Next sequence number = highest existing + 1 (every migration starts with 4 digits).
# Measure-Object returns Maximum as a Double on Windows PowerShell 5.1, so cast
# before formatting - the "d4" format specifier only accepts integral types.
$maxNumber = Get-ChildItem -Path $migrationsDir -Filter "*.sql" |
    ForEach-Object { [int]($_.Name.Substring(0, 4)) } |
    Measure-Object -Maximum |
    Select-Object -ExpandProperty Maximum
$next = "{0:d4}" -f ([int]$maxNumber + 1)

$slug = ($TitleEn.ToLower() -replace "[^a-z0-9]+", "_").Trim("_")
$path = Join-Path $migrationsDir "${next}_update_${slug}.sql"

# SQLite string literals escape a quote by doubling it.
function Quote([string]$value) { return $value -replace "'", "''" }

$sql = @"
-- Site update: $TitleEn ($ReleasedAt)
-- Generated by scripts\new-site-update.ps1 - table lives in 0016_help_content.sql

INSERT INTO site_updates (version, kind, title_en, title_th, body_en, body_th, released_at) VALUES
('$(Quote $Version)', '$(Quote $Kind)',
 '$(Quote $TitleEn)',
 '$(Quote $TitleTh)',
 '$(Quote $BodyEn)',
 '$(Quote $BodyTh)',
 '$(Quote $ReleasedAt)');
"@

# UTF-8 WITHOUT a BOM: the Go migration runner feeds the file straight to SQLite,
# which would choke on a leading BOM. Set-Content -Encoding utf8 adds one on PS 5.1.
[System.IO.File]::WriteAllText($path, $sql, (New-Object System.Text.UTF8Encoding $false))
Write-Host "==> created $path"
Write-Host "restart the backend (make restart) to apply it"
